### PR TITLE
Proofread. Update with minor edits 2017-02-23

### PR DESCRIPTION
**Pull request by FedericoEsparza**
Fascinating topic.
 
How are you keeping up with the resolution? It seems tough.

### CODE REVIEW

**Comment by tansaku** [comment]
mixed results I'd say :-)

**Comment by tansaku** [comment]
definitely some successes :-)

**Comment by tansaku** [comment]
how would you say I'm doing? :-)

**Comment by FedericoEsparza** [comment]
Good, I'd say, but perhaps you're being too critical of yourself in the first place.
 
Be the self that you are.
 
It's good to work on improvement. A mistake is an opportunity. 
  
There's the danger of overcorrecting in your approach, however, and inadvertently challenging someone with too many questions; putting them on the spot.
 
A graceful deflection, in the moment, might be best.

**Comment by tansaku** [comment]
great points @FedericoEsparza - thanks!

**Pull request merged**
